# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTrlP2QXmzK55bp5YksuYVI-a476bev0
"""

import numpy as np
import pandas as pd
from csv import reader

employee_list = pd.read_csv("CCMLEmployeeData.csv")

emp_domain = pd.DataFrame(employee_list['Domain'].value_counts()).reset_index()
emp_events = pd.DataFrame(employee_list['Event1'].value_counts()).reset_index()

emp_domain.rename(columns={'index':'domain'},inplace=True)
emp_events.rename(columns={'index':'event'},inplace=True)

Domain = {}
Event = {}
for domain in emp_domain['domain']:
    Domain[domain]=domain.lower().split()
for event in emp_events['event']:
    Event[event]=event.lower()[:-1].split()

Domain['Security'].append('cyber')
Domain['Security'].append('hacking')
Domain['Coding'].append('cod')
Domain['Mobile Applications'].append('android')
Domain['Networking'].append('network')
Domain['Development Processes'].remove('processes')
Domain['Machine Learning'].remove('learning')
Domain['C'].append(' c ')
Domain['C'].remove('c')
Domain['Coding'].remove('coding')
Domain['Machine Learning'].append('nlp')
Domain['Machine Learning'].append('natural language processing')
Domain['Higher Education'].append('master')
Domain['Artificial Intelligence'].append('deep learning')
Domain['Artificial Intelligence'].remove('intelligence')
Domain['Web Development'].remove('development')
Domain['Web Development'].remove('web')
Domain['Web Development'].append('web development')
Domain['Web Development'].append('website')

Event['Certifications'].append('certif')
Event['Certifications'].remove('certification')
Event['Internships'].append('intern')
Event['Hackathons'].append('thon')

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
#  Removing stopwords
def textPreprocessing(employee_list):

    words = employee_list.split()
    removeStopwords = [word for word in words if word.lower() not in stopwords.words('english')]
    
    return removeStopwords

def prefrences(words):
    text = ' '.join(words)
    i = True
    domain_list = []
    for domain in emp_domain['domain']:
        for item1 in Domain[domain]:
            if item1 in text.lower():
                domain_list.append(domain)
                i = False
    if i:
        domain_list.append('Other')
    event_list = []
    for event in emp_events['event']:
        for item2 in Event[event]:
            if item2 in text.lower():
                event_list.append(event)
    return domain_list,event_list
strings = []
with open('input1.csv', 'r') as read_obj:
    csv_reader = reader(read_obj)
    for row in csv_reader:
        strings.append(row)
strings = strings[1:]
strings = sum(strings, [])

temp = []
dict = {}
for item in strings:
    words = textPreprocessing(item)
    pref = prefrences(words)
    t = []
    for D in list(set(pref[0])):
        if pref[1]:
            for E in list(set(pref[1])):
                row = list(employee_list[(employee_list['Domain']==D)&((employee_list['Event1']==E)|(employee_list['Event2']==E))]['Name'])
                t.append(row)
        else:
            row = list(employee_list[(employee_list['Domain']==D)]['Name'])
            dict[item]=row
    if t:
        temp_t = sum(t, [])
        dict[item]=list(set(temp_t))
dict

new_df = pd.DataFrame()
for key, val in zip(list(dict.keys()),list(dict.values())):
    new_df = new_df.append({'Event' : key , 'Employees-to-recommend' : ', '.join(val)},ignore_index=True)
new_df = new_df[['Event','Employees-to-recommend']]
new_df.to_excel('Output.xlsx',index=False)